/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicProfilesIndexRouteImport } from './routes/api/public/profiles/index'
import { Route as ApiPublicProfilesIdIndexRouteImport } from './routes/api/public/profiles/$id/index'
import { Route as ApiPublicProfilesIdEventsRouteImport } from './routes/api/public/profiles/$id/events'
import { Route as ApiPublicProfilesIdSuggestionsRouteImport } from './routes/api/public/profiles/$id/suggestions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProfilesIndexRoute = ApiPublicProfilesIndexRouteImport.update({
  id: '/api/public/profiles/',
  path: '/api/public/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProfilesIdIndexRoute =
  ApiPublicProfilesIdIndexRouteImport.update({
    id: '/api/public/profiles/$id/',
    path: '/api/public/profiles/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProfilesIdEventsRoute =
  ApiPublicProfilesIdEventsRouteImport.update({
    id: '/api/public/profiles/$id/events',
    path: '/api/public/profiles/$id/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProfilesIdSuggestionsRoute =
  ApiPublicProfilesIdSuggestionsRouteImport.update({
    id: '/api/public/profiles/$id/suggestions',
    path: '/api/public/profiles/$id/suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/profiles/': typeof ApiPublicProfilesIndexRoute
  '/api/public/profiles/$id/events': typeof ApiPublicProfilesIdEventsRoute
  '/api/public/profiles/$id/suggestions': typeof ApiPublicProfilesIdSuggestionsRoute
  '/api/public/profiles/$id/': typeof ApiPublicProfilesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/profiles': typeof ApiPublicProfilesIndexRoute
  '/api/public/profiles/$id/events': typeof ApiPublicProfilesIdEventsRoute
  '/api/public/profiles/$id/suggestions': typeof ApiPublicProfilesIdSuggestionsRoute
  '/api/public/profiles/$id': typeof ApiPublicProfilesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/profiles/': typeof ApiPublicProfilesIndexRoute
  '/api/public/profiles/$id/events': typeof ApiPublicProfilesIdEventsRoute
  '/api/public/profiles/$id/suggestions': typeof ApiPublicProfilesIdSuggestionsRoute
  '/api/public/profiles/$id/': typeof ApiPublicProfilesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/profiles/'
    | '/api/public/profiles/$id/events'
    | '/api/public/profiles/$id/suggestions'
    | '/api/public/profiles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/profiles'
    | '/api/public/profiles/$id/events'
    | '/api/public/profiles/$id/suggestions'
    | '/api/public/profiles/$id'
  id:
    | '__root__'
    | '/'
    | '/api/public/profiles/'
    | '/api/public/profiles/$id/events'
    | '/api/public/profiles/$id/suggestions'
    | '/api/public/profiles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicProfilesIndexRoute: typeof ApiPublicProfilesIndexRoute
  ApiPublicProfilesIdEventsRoute: typeof ApiPublicProfilesIdEventsRoute
  ApiPublicProfilesIdSuggestionsRoute: typeof ApiPublicProfilesIdSuggestionsRoute
  ApiPublicProfilesIdIndexRoute: typeof ApiPublicProfilesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/': {
      id: '/api/public/profiles/'
      path: '/api/public/profiles'
      fullPath: '/api/public/profiles/'
      preLoaderRoute: typeof ApiPublicProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/$id/': {
      id: '/api/public/profiles/$id/'
      path: '/api/public/profiles/$id'
      fullPath: '/api/public/profiles/$id/'
      preLoaderRoute: typeof ApiPublicProfilesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/$id/events': {
      id: '/api/public/profiles/$id/events'
      path: '/api/public/profiles/$id/events'
      fullPath: '/api/public/profiles/$id/events'
      preLoaderRoute: typeof ApiPublicProfilesIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/$id/suggestions': {
      id: '/api/public/profiles/$id/suggestions'
      path: '/api/public/profiles/$id/suggestions'
      fullPath: '/api/public/profiles/$id/suggestions'
      preLoaderRoute: typeof ApiPublicProfilesIdSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicProfilesIndexRoute: ApiPublicProfilesIndexRoute,
  ApiPublicProfilesIdEventsRoute: ApiPublicProfilesIdEventsRoute,
  ApiPublicProfilesIdSuggestionsRoute: ApiPublicProfilesIdSuggestionsRoute,
  ApiPublicProfilesIdIndexRoute: ApiPublicProfilesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
